# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoincidenceExampleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CoincidenceExample(object):
    def setupUi(self, CoincidenceExample):
        CoincidenceExample.setObjectName("CoincidenceExample")
        CoincidenceExample.resize(889, 753)
        self.centralwidget = QtWidgets.QWidget(CoincidenceExample)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 4, 1, 1)
        self.delayB = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delayB.sizePolicy().hasHeightForWidth())
        self.delayB.setSizePolicy(sizePolicy)
        self.delayB.setMinimum(-99999)
        self.delayB.setMaximum(99999)
        self.delayB.setObjectName("delayB")
        self.gridLayout.addWidget(self.delayB, 4, 2, 1, 1)
        self.channelA = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelA.sizePolicy().hasHeightForWidth())
        self.channelA.setSizePolicy(sizePolicy)
        self.channelA.setMinimum(-99)
        self.channelA.setProperty("value", 1)
        self.channelA.setObjectName("channelA")
        self.gridLayout.addWidget(self.channelA, 2, 1, 1, 1)
        self.channelB = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelB.sizePolicy().hasHeightForWidth())
        self.channelB.setSizePolicy(sizePolicy)
        self.channelB.setMinimum(-99)
        self.channelB.setProperty("value", 2)
        self.channelB.setObjectName("channelB")
        self.gridLayout.addWidget(self.channelB, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.delayA = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delayA.sizePolicy().hasHeightForWidth())
        self.delayA.setSizePolicy(sizePolicy)
        self.delayA.setMinimum(-99999)
        self.delayA.setMaximum(99999)
        self.delayA.setObjectName("delayA")
        self.gridLayout.addWidget(self.delayA, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.triggerB = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.triggerB.setMinimum(-2.5)
        self.triggerB.setMaximum(2.5)
        self.triggerB.setSingleStep(0.1)
        self.triggerB.setProperty("value", 0.5)
        self.triggerB.setObjectName("triggerB")
        self.gridLayout.addWidget(self.triggerB, 4, 3, 1, 1)
        self.testsignalA = QtWidgets.QCheckBox(self.centralwidget)
        self.testsignalA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.testsignalA.setAutoFillBackground(False)
        self.testsignalA.setStyleSheet("")
        self.testsignalA.setText("")
        self.testsignalA.setChecked(False)
        self.testsignalA.setAutoRepeat(False)
        self.testsignalA.setObjectName("testsignalA")
        self.gridLayout.addWidget(self.testsignalA, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.triggerA = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.triggerA.setMinimum(-2.5)
        self.triggerA.setMaximum(2.5)
        self.triggerA.setSingleStep(0.1)
        self.triggerA.setProperty("value", 0.5)
        self.triggerA.setObjectName("triggerA")
        self.gridLayout.addWidget(self.triggerA, 2, 3, 1, 1)
        self.testsignalB = QtWidgets.QCheckBox(self.centralwidget)
        self.testsignalB.setText("")
        self.testsignalB.setObjectName("testsignalB")
        self.gridLayout.addWidget(self.testsignalB, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.coincidenceWindow = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coincidenceWindow.sizePolicy().hasHeightForWidth())
        self.coincidenceWindow.setSizePolicy(sizePolicy)
        self.coincidenceWindow.setMinimum(1)
        self.coincidenceWindow.setMaximum(9999)
        self.coincidenceWindow.setProperty("value", 1000)
        self.coincidenceWindow.setObjectName("coincidenceWindow")
        self.gridLayout.addWidget(self.coincidenceWindow, 0, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 6, 1, 1)
        self.correlationBinwidth = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlationBinwidth.sizePolicy().hasHeightForWidth())
        self.correlationBinwidth.setSizePolicy(sizePolicy)
        self.correlationBinwidth.setMinimum(1)
        self.correlationBinwidth.setMaximum(9999)
        self.correlationBinwidth.setProperty("value", 40)
        self.correlationBinwidth.setObjectName("correlationBinwidth")
        self.gridLayout.addWidget(self.correlationBinwidth, 2, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 6, 1, 1)
        self.correlationBins = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlationBins.sizePolicy().hasHeightForWidth())
        self.correlationBins.setSizePolicy(sizePolicy)
        self.correlationBins.setMinimum(1)
        self.correlationBins.setMaximum(99999)
        self.correlationBins.setProperty("value", 1000)
        self.correlationBins.setObjectName("correlationBins")
        self.gridLayout.addWidget(self.correlationBins, 4, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.plotWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plotWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.plotWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        CoincidenceExample.setCentralWidget(self.centralwidget)
        self.label_2.setBuddy(self.label_2)

        self.retranslateUi(CoincidenceExample)
        QtCore.QMetaObject.connectSlotsByName(CoincidenceExample)
        CoincidenceExample.setTabOrder(self.channelA, self.delayA)
        CoincidenceExample.setTabOrder(self.delayA, self.channelB)
        CoincidenceExample.setTabOrder(self.channelB, self.delayB)
        CoincidenceExample.setTabOrder(self.delayB, self.startButton)
        CoincidenceExample.setTabOrder(self.startButton, self.stopButton)
        CoincidenceExample.setTabOrder(self.stopButton, self.clearButton)
        CoincidenceExample.setTabOrder(self.clearButton, self.saveButton)

    def retranslateUi(self, CoincidenceExample):
        _translate = QtCore.QCoreApplication.translate
        CoincidenceExample.setWindowTitle(_translate("CoincidenceExample", "CoincidenceExample"))
        self.label_13.setText(_translate("CoincidenceExample", "Test signal"))
        self.delayB.setSuffix(_translate("CoincidenceExample", " ps"))
        self.label_2.setText(_translate("CoincidenceExample", "Input delay"))
        self.delayA.setSuffix(_translate("CoincidenceExample", " ps"))
        self.label_11.setText(_translate("CoincidenceExample", "B:"))
        self.label_10.setText(_translate("CoincidenceExample", "A:"))
        self.label.setText(_translate("CoincidenceExample", "Input channel"))
        self.label_5.setText(_translate("CoincidenceExample", "Coincidence window"))
        self.label_12.setText(_translate("CoincidenceExample", "Trigger level"))
        self.triggerB.setSuffix(_translate("CoincidenceExample", " V"))
        self.triggerA.setSuffix(_translate("CoincidenceExample", " V"))
        self.coincidenceWindow.setSuffix(_translate("CoincidenceExample", " ps"))
        self.label_6.setText(_translate("CoincidenceExample", "Correlation bin width"))
        self.correlationBinwidth.setSuffix(_translate("CoincidenceExample", " ps"))
        self.label_7.setText(_translate("CoincidenceExample", "Correlation bins"))
        self.startButton.setText(_translate("CoincidenceExample", "Start"))
        self.stopButton.setText(_translate("CoincidenceExample", "Stop"))
        self.clearButton.setText(_translate("CoincidenceExample", "Clear"))
        self.saveButton.setText(_translate("CoincidenceExample", "Save"))

