# Generated by Django 3.2.5 on 2022-06-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_order', models.IntegerField(unique=True, verbose_name='lab order')),
                ('pi_name', models.CharField(max_length=30, verbose_name='principal investigator')),
                ('pi_email', models.EmailField(max_length=254, verbose_name='lab email')),
                ('pi_phone', models.CharField(max_length=15, verbose_name='lab contact')),
                ('location', models.CharField(max_length=50, verbose_name='lab address')),
                ('token', models.CharField(max_length=30, verbose_name='lab token')),
                ('default_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name', verbose_name='lab name')),
            ],
            options={
                'verbose_name': 'Terminal Laboratory',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('resource', models.CharField(max_length=10, verbose_name='resource type (EPs or SPDs)')),
                ('in_ch', models.IntegerField(verbose_name='input channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation information',
            },
        ),
        migrations.CreateModel(
            name='SPDsLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ch', models.IntegerField(verbose_name='input channel')),
                ('out_ch', models.IntegerField(verbose_name='output channel')),
                ('linkage', models.BooleanField(verbose_name='linkage status')),
                ('in_use', models.BooleanField(default=False, verbose_name='in use or idle')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubinfo.laboratory')),
            ],
            options={
                'verbose_name': 'SPD Channels Linkage Status',
                'unique_together': {('in_ch', 'out_ch')},
            },
        ),
        migrations.CreateModel(
            name='EPsLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ch', models.IntegerField(verbose_name='input channel')),
                ('out_ch', models.IntegerField(verbose_name='output channel')),
                ('linkage', models.BooleanField(verbose_name='linkage status')),
                ('in_use', models.BooleanField(default=False, verbose_name='in use or idle')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubinfo.laboratory')),
            ],
            options={
                'verbose_name': 'Entangled-Photon Sources Linkage Status',
                'unique_together': {('in_ch', 'out_ch')},
            },
        ),
    ]
